=== mgerni/Taskapp_Public/tasks/task-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Task",
  "description": "Schema for representing a task object",
  "type": "object",
  "properties": {
    "_id": {
      "type": "integer",
      "description": "Unique identifier for the task - Only unique within each task tier"
    },
    "name": {
      "type": "string",
      "description": "Name of the task"
    },
    "isLms": {
      "type": "boolean",
      "description": "Indicates whether the task is related to Last Man Standing (LMS)"
    },
    "tip": {
      "type": "string",
      "description": "Hint text for the task"
    },
    "wikiLink": {
      "type": "string",
      "format": "uri",
      "description": "URL linking to the wiki page providing more information about the task"
    },
    "wikiImage": {
      "type": "string",
      "format": "uri",
      "description": "URL linking to an image representing the task from the wiki"
    },
    "assetImage": {
      "type": "string",
      "description": "Name of the asset image for the task"
    },
    "colLogData": {
      "type": "object",
      "description": "Data used to check the task has been completed via the users Collection Log",
      "properties": {
        "category": {
          "type": "string",
          "description": "Category to which the task belongs in the Collection Log"
        },
        "logName": {
          "type": "string",
          "description": "Name of the task entry in the Collection Log"
        },
        "include": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Items to include when checking the Collection Log for this task"
        },
        "exclude": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Items to exclude when checking the Collection Log for this task"
        },
        "logCount": {
          "type": "integer",
          "description": "Number of items to check for in the Collection Log"
        }
      },
      "required": ["category", "logName",  "logCount"]
    }
  },
  "required": ["_id", "name", "wikiLink", "assetImage"]
}

=== mgerni/Taskapp_Public/tasks/bossPets.json
[
    {
        "_id": 1,
        "name": "Abyssal orphan",
        "isLms": false,
        "assetImage": "Abyssal_orphan.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Abyssal_orphan"
    },
    {
        "_id": 2,
        "name": "Baby mole",
        "isLms": false,
        "assetImage": "Baby_mole.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Baby_mole"
    },
    {
        "_id": 3,
        "name": "Callisto cub",
        "isLms": false,
        "assetImage": "Callisto_cub.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Callisto_cub"
    },
    {
        "_id": 4,
        "name": "Hellpuppy",
        "isLms": false,
        "assetImage": "Hellpuppy.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Hellpuppy"
    },
    {
        "_id": 5,
        "name": "Ikkle hydra",
        "isLms": false,
        "assetImage": "Ikkle_hydra.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Ikkle_hydra"
    },
    {
        "_id": 6,
        "name": "Jal-nib-rek/Tzrek-zuk",
        "isLms": false,
        "assetImage": "Jal-nib-rek.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Jal-nib-rek"
    },
    {
        "_id": 7,
        "name": "Kalphite princess",
        "isLms": false,
        "assetImage": "Kalphite_princess_2nd_form.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Kalphite_princess"
    },
    {
        "_id": 8,
        "name": "Lil' zik",
        "isLms": false,
        "assetImage": "Lil_zik.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Lil%27_zik"
    },
    {
        "_id": 9,
        "name": "Little nightmare",
        "isLms": false,
        "assetImage": "Little_nightmare.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Little_nightmare"
    },
    {
        "_id": 10,
        "name": "Muphin",
        "isLms": false,
        "assetImage": "Muphin_detail.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Muphin"
    },
    {
        "_id": 11,
        "name": "Nexling",
        "isLms": false,
        "assetImage": "Nexling.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Nexling"
    },
    {
        "_id": 12,
        "name": "Noon/Midnight",
        "isLms": false,
        "assetImage": "Noon.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Noon"
    },
    {
        "_id": 13,
        "name": "Olmlet",
        "isLms": false,
        "assetImage": "Olmlet.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Olmlet"
    },
    {
        "_id": 14,
        "name": "Pet chaos elemental",
        "isLms": false,
        "assetImage": "Pet_chaos_elemental.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_chaos_elemental"
    },
    {
        "_id": 15,
        "name": "Pet dagannoth prime",
        "isLms": false,
        "assetImage": "Pet_dagannoth_prime.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_dagannoth_prime"
    },
    {
        "_id": 16,
        "name": "Pet dagannoth rex",
        "isLms": false,
        "assetImage": "Pet_dagannoth_rex.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_dagannoth_rex"
    },
    {
        "_id": 17,
        "name": "Pet dagannoth supreme",
        "isLms": false,
        "assetImage": "Pet_dagannoth_supreme.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_dagannoth_supreme"
    },
    {
        "_id": 18,
        "name": "Pet dark core/corporeal critter",
        "isLms": false,
        "assetImage": "Pet_dark_core.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_dark_core"
    },
    {
        "_id": 19,
        "name": "Pet general graardor",
        "isLms": false,
        "assetImage": "Pet_general_graardor.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_general_graardor"
    },
    {
        "_id": 20,
        "name": "Pet k'ril tsutsaroth",
        "isLms": false,
        "assetImage": "Pet_kril_tsutsaroth.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_k%27ril_tsutsaroth"
    },
    {
        "_id": 21,
        "name": "Pet kraken",
        "isLms": false,
        "assetImage": "Pet_kraken.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_kraken"
    },
    {
        "_id": 22,
        "name": "Pet kree'arra",
        "isLms": false,
        "assetImage": "Pet_kreearra.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_kree%27arra"
    },
    {
        "_id": 23,
        "name": "Pet smoke devil",
        "isLms": false,
        "assetImage": "Pet_smoke_devil.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_smoke_devil"
    },
    {
        "_id": 24,
        "name": "Pet snakeling",
        "isLms": false,
        "assetImage": "Pet_snakeling.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_snakeling"
    },
    {
        "_id": 25,
        "name": "Pet zilyana",
        "isLms": false,
        "assetImage": "Pet_zilyana.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_zilyana"
    },
    {
        "_id": 26,
        "name": "Prince black dragon",
        "isLms": false,
        "assetImage": "Prince_black_dragon.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Prince_black_dragon"
    },
    {
        "_id": 27,
        "name": "Scorpia's offspring",
        "isLms": false,
        "assetImage": "Scorpias_offspring.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Scorpia offspring"
    },
    {
        "_id": 28,
        "name": "Scurry",
        "isLms": false,
        "assetImage": "Scurry.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Scurry"
    },
    {
        "_id": 29,
        "name": "Skotos",
        "isLms": false,
        "assetImage": "Skotos.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Skotos"
    },
    {
        "_id": 30,
        "name": "Sraracha",
        "isLms": false,
        "assetImage": "Sraracha.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Sraracha"
    },
    {
        "_id": 31,
        "name": "Tzrek-jad",
        "isLms": false,
        "assetImage": "Tzrek-jad.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Tzrek-jad"
    },
    {
        "_id": 32,
        "name": "Tumeken's guardian",
        "isLms": false,
        "assetImage": "Tumeken's_Guardian.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Tumeken%27s_guardian"
    },
    {
        "_id": 33,
        "name": "Venenatis spiderling",
        "isLms": false,
        "assetImage": "Venenatis_spiderling.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Venenatis_spiderling"
    },
    {
        "_id": 34,
        "name": "Vet'ion jr",
        "isLms": false,
        "assetImage": "Vetion_jr.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Vetion_junior"
    },
    {
        "_id": 35,
        "name": "Vorki",
        "isLms": false,
        "assetImage": "Vorki.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Vorki"
    },
    {
        "_id": 36,
        "name": "Smol Heredit",
        "isLms": false,
        "assetImage": "smol_heredit.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Smol_heredit"
    }
]

=== mgerni/Taskapp_Public/tasks/otherPets.json
[
    {
        "_id": 1,
        "name": "Bloodhound",
        "isLms": false,
        "assetImage": "Bloodhound.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Bloodhound"
    },
    {
        "_id": 2,
        "name": "Chompy chick",
        "isLms": false,
        "assetImage": "Chompy_chick.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Chompy_chick"
    },
    {
        "_id": 3,
        "name": "Herbi",
        "isLms": false,
        "assetImage": "Herbi.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Herbi"
    },
    {
        "_id": 4,
        "name": "Pet penance queen",
        "isLms": false,
        "assetImage": "Pet_penance_queen.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Pet_penance_queen"
    },
    {
        "_id": 5,
        "name": "Phoenix",
        "isLms": false,
        "assetImage": "Phoenix.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Phoenix"
    },
    {
        "_id": 6,
        "name": "Youngllef",
        "isLms": false,
        "assetImage": "Youngllef.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Youngllef"
    },
    {
        "_id": 7,
        "name": "Smolcano",
        "isLms": false,
        "assetImage": "Smolcano.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Smolcano"
    },
    {
        "_id": 8,
        "name": "Tiny Tempor",
        "isLms": false,
        "assetImage": "Tiny_Tempor_chathead.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Tiny_tempor"
    },
    {
        "_id": 9,
        "name": "Lil' creator",
        "isLms": false,
        "assetImage": "Lil_Creator_chathead.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Lil%27_creator"
    },
    {
        "_id": 10,
        "name": "Abyssal protector",
        "isLms": false,
        "assetImage": "Abyssal_protector_chathead.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Abyssal_protector"
    }
]

=== mgerni/Taskapp_Public/tasks/skillPets.json
[
    {
        "_id": 1,
        "name": "Baby chinchompa",
        "isLms": false,
        "assetImage": "Baby_chinchompa_black.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Baby_chinchompa"
    },
    {
        "_id": 2,
        "name": "Beaver",
        "isLms": false,
        "assetImage": "Beaver.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Beaver"
    },
    {
        "_id": 3,
        "name": "Giant squirrel",
        "isLms": false,
        "assetImage": "Giant_squirrel.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Giant_squirrel"
    },
    {
        "_id": 4,
        "name": "Heron",
        "isLms": false,
        "assetImage": "Heron.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Heron"
    },
    {
        "_id": 5,
        "name": "Rift guardian",
        "isLms": false,
        "assetImage": "Rift_guardian_fire.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Rift_guardian"
    },
    {
        "_id": 6,
        "name": "Rock golem",
        "isLms": false,
        "assetImage": "Rock_golem.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Rock_golem"
    },
    {
        "_id": 7,
        "name": "Rocky",
        "isLms": false,
        "assetImage": "Rocky.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Rocky"
    },
    {
        "_id": 8,
        "name": "Tangleroot",
        "isLms": false,
        "assetImage": "Tangleroot.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Tangleroot"
    },
    {
        "_id": 9,
        "name": "Quetzin",
        "isLms": false,
        "assetImage": "quetzin.png",
        "wikiLink": "https://oldschool.runescape.wiki/w/Quetzin"
    }
]
